import { build } from "esbuild";
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const uiDir = resolve(scriptDir, "..");
const distDir = resolve(uiDir, "dist");

await mkdir(distDir, { recursive: true });
await build({
  bundle: true,
  entryPoints: [resolve(uiDir, "src/main.ts")],
  format: "esm",
  legalComments: "none",
  minify: false,
  outfile: resolve(distDir, "app.js"),
  platform: "browser",
  sourcemap: true,
  target: "es2022",
  banner: {
    js: "/* Generated by ui/scripts/build.mjs. Edit ui/src instead. */",
  },
});

const appBundlePath = resolve(distDir, "app.js");
const appBundle = await readFile(appBundlePath, "utf8");
await writeFile(appBundlePath, appBundle.replace(/[ \t]+$/gmu, ""));

await cp(resolve(uiDir, "index.html"), resolve(distDir, "index.html"));
await cp(resolve(uiDir, "style.css"), resolve(distDir, "style.css"));
await cp(appBundlePath, resolve(uiDir, "app.js"));
