//! Static UI hosting.
//!
//! The server is the only thing a client needs to know about: it serves the UI
//! bundle and the API from the same origin, so the UI derives its server
//! address from `window.location.origin` and has nothing to configure. See
//! `docs/ui.md` for the client contract.
//!
//! The client is **compiled into the binary**: `apps/app/dist` is embedded at
//! build time (`build.rs`), so a server carries its UI with it and needs no
//! configuration to serve one. One artifact to install, one thing to upgrade,
//! no bundle path to get wrong.
//!
//! * **Embedded** (always) — the product app, served from this binary.
//! * **Proxy** (`LOOM_UI_PROXY`) — development only: reverse-proxy to the
//!   frontend dev server, so the UI can be edited with hot reload against the
//!   real server. Nothing else overrides the embedded bundle.
//!
//! A buildless reference client used to be compiled in here alongside it. It is
//! gone (W-586 / W-588): two clients meant two behaviours to keep in step, and
//! the one that shipped by default was the one nobody used.
//!
//! Everything here is deliberate about one thing: an unmatched *client* path
//! falls back to `index.html`, but an unmatched `/api`, `/ws` or `/internal/ws`
//! path must not,
//! or a mistyped API route would answer with an HTML page.

use std::path::{Component, Path, PathBuf};
use std::sync::Arc;

use axum::body::Body;
use axum::extract::{Request, State};
use axum::http::{header, HeaderValue, Method, StatusCode, Uri};
use axum::response::{IntoResponse, Response};

use crate::state::AppState;

const HTML: &str = "text/html; charset=utf-8";
const JS: &str = "text/javascript; charset=utf-8";
const CSS: &str = "text/css; charset=utf-8";

/// Where the server answers a UI request from.
#[derive(Clone)]
pub struct Ui {
    source: UiSource,
}

#[derive(Clone)]
enum UiSource {
    Embedded,
    Proxy(Arc<ProxyClient>),
    Disabled,
}

/// The product app, generated by `build.rs` from `apps/app/dist`.
mod assets {
    include!(concat!(env!("OUT_DIR"), "/ui_assets.rs"));
}

impl std::fmt::Debug for Ui {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.source {
            UiSource::Embedded => f.write_str("Ui::Embedded"),
            UiSource::Proxy(proxy) => f.debug_tuple("Ui::Proxy").field(proxy).finish(),
            UiSource::Disabled => f.write_str("Ui::Disabled"),
        }
    }
}

impl Ui {
    /// Resolves the configured source.
    ///
    /// The embedded bundle is the source; `proxy` is the one override, and it
    /// exists for development. There is deliberately no path to a bundle on
    /// disk: the binary carries the client, so an installed server cannot be
    /// pointed at a different one than the release shipped.
    pub fn from_config(proxy: Option<String>) -> Result<Self, String> {
        let source = match proxy {
            Some(base) => UiSource::Proxy(Arc::new(ProxyClient::new(&base)?)),
            None => UiSource::Embedded,
        };
        Ok(Self { source })
    }

    /// Serves nothing. Used by tests that assert on API behaviour only.
    pub fn disabled() -> Self {
        Self {
            source: UiSource::Disabled,
        }
    }

    /// A human-readable description of the active source, for the startup log.
    pub fn describe(&self) -> String {
        match &self.source {
            UiSource::Embedded => format!("embedded product app ({} files)", assets::FILE_COUNT),
            UiSource::Proxy(proxy) => format!("dev-server proxy {}", proxy.base),
            UiSource::Disabled => "disabled".into(),
        }
    }

    /// Answers one request that fell through the API routes.
    pub async fn handle(self, request: Request) -> Response {
        let path = request.uri().path().to_owned();

        // A client route is allowed to fall back to index.html; an API or
        // socket path is not. Otherwise `GET /api/v1/typo` would return the
        // SPA shell with a 200, which is exactly the kind of failure that is
        // hard to diagnose from the browser.
        if path == "/ws" || path == "/internal/ws" || path == "/api" || path.starts_with("/api/") {
            return not_found();
        }

        match self.source {
            UiSource::Disabled => not_found(),
            UiSource::Embedded => embedded_response(&path, request.method()),
            UiSource::Proxy(proxy) => proxy.forward(request).await,
        }
    }
}

/// Axum fallback handler.
pub async fn serve(State(state): State<AppState>, request: Request) -> Response {
    state.ui.clone().handle(request).await
}

/* ------------------------------------------------------------------ */
/* Embedded product app                                                */
/* ------------------------------------------------------------------ */

/// Serves one file out of the binary.
///
/// The rules are the ones a static client needs and no more: a file that is
/// embedded is served with its type and cache policy, a path without an
/// extension falls back to the entry document so history routing works, and a
/// missing *asset* is an honest 404 rather than the shell — a browser that gets
/// HTML where it asked for JavaScript reports a syntax error that hides the
/// real mistake.
fn embedded_response(path: &str, method: &Method) -> Response {
    if !is_read(method) {
        return not_found();
    }
    let Some(relative) = sanitize(path) else {
        return not_found();
    };
    let key = relative.to_string_lossy().replace('\\', "/");
    if let Some(bytes) = assets::get(&key) {
        return asset_response(
            Body::from(bytes),
            content_type_for(&relative),
            cache_for(path),
        );
    }
    if is_client_route(path) {
        return asset_response(Body::from(assets::INDEX_HTML), HTML, "no-cache");
    }
    not_found()
}

/// Maps a request path to a path under the UI root, rejecting traversal.
///
/// Nothing is served from outside `root`: `..`, absolute paths and prefixes are
/// refused rather than normalised, because a silently normalised path is a
/// sandbox escape waiting for the next refactor.
fn sanitize(path: &str) -> Option<PathBuf> {
    let trimmed = path.trim_start_matches('/');
    let mut out = PathBuf::new();
    for component in Path::new(trimmed).components() {
        match component {
            Component::Normal(part) => out.push(part),
            Component::CurDir => {}
            Component::RootDir | Component::ParentDir | Component::Prefix(_) => return None,
        }
    }
    // `/` and `/foo/` resolve to their `index.html`.
    if out.as_os_str().is_empty() || path.ends_with('/') {
        out.push("index.html");
    }
    Some(out)
}

/// Whether a path may fall back to the SPA shell. Files with an extension are
/// requested assets and must 404 honestly.
fn is_client_route(path: &str) -> bool {
    Path::new(path).extension().is_none()
}

fn is_read(method: &Method) -> bool {
    method == Method::GET || method == Method::HEAD
}

fn asset_response(body: Body, content_type: &'static str, cache: &'static str) -> Response {
    let mut response = Response::new(body);
    response
        .headers_mut()
        .insert(header::CONTENT_TYPE, HeaderValue::from_static(content_type));
    response
        .headers_mut()
        .insert(header::CACHE_CONTROL, HeaderValue::from_static(cache));
    response
}

fn content_type_for(path: &Path) -> &'static str {
    match path.extension().and_then(|ext| ext.to_str()).unwrap_or("") {
        "html" | "htm" => HTML,
        "js" | "mjs" => JS,
        "css" => CSS,
        "json" | "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "wasm" => "application/wasm",
        "txt" => "text/plain; charset=utf-8",
        "webmanifest" => "application/manifest+json",
        _ => "application/octet-stream",
    }
}

/// Content-hashed build assets are immutable; everything else is revalidated so
/// a redeploy is picked up without a hard refresh.
fn cache_for(path: &str) -> &'static str {
    if path.ends_with("index.html") || path.ends_with('/') || path == "/" {
        "no-cache"
    } else if path.contains("/assets/") {
        "public, max-age=31536000, immutable"
    } else {
        "public, max-age=3600"
    }
}

/* ------------------------------------------------------------------ */
/* Dev-server reverse proxy                                            */
/* ------------------------------------------------------------------ */

/// The development shape: forward unmatched requests to a frontend dev server.
///
/// WebSocket upgrades are tunnelled too, so Vite's HMR socket keeps working
/// while `/api`, `/ws` and `/internal/ws` stay on loom-server. The client therefore needs no
/// CORS configuration and no second origin.
pub struct ProxyClient {
    base: Uri,
    client: hyper_util::client::legacy::Client<
        hyper_util::client::legacy::connect::HttpConnector,
        Body,
    >,
}

impl std::fmt::Debug for ProxyClient {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ProxyClient")
            .field("base", &self.base.to_string())
            .finish()
    }
}

impl ProxyClient {
    /// Builds a client for an absolute base URL, e.g. `http://127.0.0.1:5173`.
    pub fn new(base: &str) -> Result<Self, String> {
        let base: Uri = base
            .trim()
            .parse()
            .map_err(|error| format!("invalid --ui-proxy url: {error}"))?;
        if base.scheme().is_none() || base.authority().is_none() {
            return Err("--ui-proxy must be an absolute URL, e.g. http://127.0.0.1:5173".into());
        }
        let client =
            hyper_util::client::legacy::Client::builder(hyper_util::rt::TokioExecutor::new())
                .build_http();
        Ok(Self { base, client })
    }

    async fn forward(self: Arc<Self>, request: Request) -> Response {
        // An upgrade request has an empty body, so its parts can be cloned
        // before the request is consumed by `hyper::upgrade::on`.
        if request.headers().get(header::UPGRADE).is_some() {
            let method = request.method().clone();
            let uri = request.uri().clone();
            let headers = request.headers().clone();
            let incoming = hyper::upgrade::on(request);
            return self
                .forward_parts(method, uri, headers, Body::empty(), Some(incoming))
                .await;
        }
        let (parts, body) = request.into_parts();
        self.forward_parts(parts.method, parts.uri, parts.headers, body, None)
            .await
    }

    async fn forward_parts(
        self: &Arc<Self>,
        method: Method,
        uri: Uri,
        headers: axum::http::HeaderMap,
        body: Body,
        incoming: Option<hyper::upgrade::OnUpgrade>,
    ) -> Response {
        let authority = match self.base.authority() {
            Some(authority) => authority.clone(),
            None => return error_response(StatusCode::BAD_GATEWAY, "proxy base has no authority"),
        };
        let path_and_query = uri.path_and_query().map(|pq| pq.as_str()).unwrap_or("/");
        let target = format!(
            "{}{}",
            self.base.to_string().trim_end_matches('/'),
            path_and_query
        );
        let target: Uri = match target.parse() {
            Ok(target) => target,
            Err(error) => {
                return error_response(
                    StatusCode::BAD_GATEWAY,
                    format!("proxy target is not a valid URL: {error}"),
                )
            }
        };

        let mut upstream = Request::new(body);
        *upstream.method_mut() = method;
        *upstream.uri_mut() = target;
        // Dev servers speak HTTP/1.1; a tunnelled upgrade must not be
        // downgraded to HTTP/2, which has no `Upgrade` mechanism.
        *upstream.version_mut() = axum::http::Version::HTTP_11;
        *upstream.headers_mut() = headers;
        upstream.headers_mut().insert(
            header::HOST,
            HeaderValue::from_str(authority.as_str())
                .unwrap_or_else(|_| HeaderValue::from_static("localhost")),
        );

        let response = match self.client.request(upstream).await {
            Ok(response) => response,
            Err(error) => {
                return error_response(
                    StatusCode::BAD_GATEWAY,
                    format!("ui proxy could not reach {}: {error}", self.base),
                )
            }
        };

        let status = response.status();
        let response_headers = response.headers().clone();

        if status == StatusCode::SWITCHING_PROTOCOLS {
            let upstream = hyper::upgrade::on(response);
            if let Some(incoming) = incoming {
                tokio::spawn(tunnel(incoming, upstream));
            }
            let mut out = Response::new(Body::empty());
            *out.status_mut() = status;
            *out.headers_mut() = response_headers;
            return out;
        }

        let mut out = Response::new(Body::new(response.into_body()));
        *out.status_mut() = status;
        *out.headers_mut() = response_headers;
        out
    }
}

/// Copies bytes in both directions until either side closes.
async fn tunnel(incoming: hyper::upgrade::OnUpgrade, upstream: hyper::upgrade::OnUpgrade) {
    let Ok((incoming, upstream)) = tokio::try_join!(incoming, upstream) else {
        return;
    };
    let mut incoming = hyper_util::rt::TokioIo::new(incoming);
    let mut upstream = hyper_util::rt::TokioIo::new(upstream);
    let _ = tokio::io::copy_bidirectional(&mut incoming, &mut upstream).await;
}

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

fn not_found() -> Response {
    error_response(StatusCode::NOT_FOUND, "not found")
}

fn error_response(status: StatusCode, message: impl Into<String>) -> Response {
    (
        status,
        axum::Json(serde_json::json!({ "error": message.into() })),
    )
        .into_response()
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::Request;
    use http_body_util::BodyExt;

    async fn body_text(response: Response) -> String {
        let bytes = response.into_body().collect().await.unwrap().to_bytes();
        String::from_utf8(bytes.to_vec()).unwrap()
    }

    #[tokio::test]
    async fn the_embedded_product_app_is_served() {
        // The bundle is compiled in, so a server always has a client to serve
        // and no configuration can change which one.
        let ui = Ui::from_config(None).unwrap();
        assert!(
            ui.describe().contains("embedded product app"),
            "{}",
            ui.describe()
        );

        let index = ui
            .clone()
            .handle(Request::builder().uri("/").body(Body::empty()).unwrap())
            .await;
        assert_eq!(index.status(), StatusCode::OK);
        assert_eq!(
            index.headers()[header::CONTENT_TYPE],
            HeaderValue::from_static(HTML)
        );
        let html = body_text(index).await;

        // The app's entry document references a content-hashed asset, and that
        // asset must come out of the same binary: an index.html without its
        // bundle answers 200 and paints nothing.
        let entry = html
            .split("src=\"")
            .nth(1)
            .and_then(|rest| rest.split('"').next())
            .expect("the app's index.html must reference a script");
        assert!(entry.starts_with("/assets/"), "{entry}");
        let asset = ui
            .clone()
            .handle(Request::builder().uri(entry).body(Body::empty()).unwrap())
            .await;
        assert_eq!(asset.status(), StatusCode::OK);
        assert_eq!(asset.headers()[header::CONTENT_TYPE], JS);
        assert!(asset.headers()[header::CACHE_CONTROL]
            .to_str()
            .unwrap()
            .contains("immutable"));
    }

    #[tokio::test]
    async fn client_routes_fall_back_to_the_shell_but_api_paths_do_not() {
        let ui = Ui::from_config(None).unwrap();

        let client = ui
            .clone()
            .handle(
                Request::builder()
                    .uri("/threads/thr_1")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await;
        assert_eq!(client.status(), StatusCode::OK);
        assert_eq!(
            client.headers()[header::CONTENT_TYPE],
            HeaderValue::from_static(HTML)
        );
        assert!(body_text(client).await.contains("<html"));

        let api = ui
            .handle(
                Request::builder()
                    .uri("/api/v1/nope")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await;
        assert_eq!(api.status(), StatusCode::NOT_FOUND);

        // A missing *asset* is a 404, not the shell: a browser handed HTML
        // where it asked for JavaScript reports a syntax error instead of the
        // real mistake.
        let asset = Ui::from_config(None)
            .unwrap()
            .handle(
                Request::builder()
                    .uri("/missing.js")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await;
        assert_eq!(asset.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn traversal_out_of_the_bundle_is_refused() {
        // Even a path that could only escape into the *filesystem* is refused
        // before the lookup: the bundle is a lookup table, and a traversal is
        // an attempt to read something that is not in it.
        let response = Ui::from_config(None)
            .unwrap()
            .handle(
                Request::builder()
                    .uri("/../secret.txt")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await;
        assert_eq!(response.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn a_relative_proxy_url_is_rejected() {
        assert!(Ui::from_config(Some("127.0.0.1:5173".into())).is_err());
    }

    #[tokio::test]
    async fn the_proxy_forwards_http_requests_to_the_dev_server() {
        use axum::routing::get;
        use std::net::SocketAddr;

        let upstream = axum::Router::new().route(
            "/hello.js",
            get(|| async { ([("content-type", JS)], "export const hello = 1;") }),
        );
        let listener = tokio::net::TcpListener::bind::<SocketAddr>("127.0.0.1:0".parse().unwrap())
            .await
            .unwrap();
        let addr = listener.local_addr().unwrap();
        tokio::spawn(async move {
            let _ = axum::serve(listener, upstream).await;
        });

        let ui = Ui::from_config(Some(format!("http://{addr}"))).unwrap();
        let response = ui
            .handle(
                Request::builder()
                    .uri("/hello.js")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await;
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(body_text(response).await, "export const hello = 1;");
    }
}
